name: genomatnn
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.13
  - slim=3.6
  - python=3.8
  - tensorflow=2.4.1
  - msprime=0.7.4
  - pyslim=0.600
  - pip=21.2.2
  - pip:
    - stdpopsim @ git+https://github.com/grahamgower/stdpopsim.git@selection
    - -r requirements.txt
